import '../power-selection.css';
import '../base.css';
import '../coins.css';
import { Engine } from '@babylonjs/core';
import type { PowerType } from './core/types';
import { SaveSystem } from './systems/SaveSystem'; import { Hud } from './ui/Hud'; import { PauseMenu } from './ui/PauseMenu'; import { VirtualJoystick } from './ui/VirtualJoystick'; import { WorldScene } from './scenes/WorldScene';
export class Game {private engine:Engine;private save=new SaveSystem();private world?:WorldScene;constructor(canvas:HTMLCanvasElement,private ui:HTMLElement){this.engine=new Engine(canvas,true,{antialias:true});}
start(){this.showTitle();addEventListener('resize',()=>this.engine.resize());}
private showTitle(){this.ui.innerHTML=`<div class="title-screen"><div class="logo"><span>THE TALES OF</span><h1>GREEN FIELDS</h1><p>A tiny stylized RPG adventure</p></div><div class="title-actions">${this.save.hasSave()?'<button data-start="continue">Continue</button>':''}<button data-start="new">New Game</button></div></div>`;this.ui.querySelector('[data-start="continue"]')?.addEventListener('click',()=>this.launch(true));this.ui.querySelector('[data-start="new"]')?.addEventListener('click',()=>this.showPowerSelection());}
private showPowerSelection(){this.ui.innerHTML=`<div class="title-screen power-screen"><div class="power-selection"><h1>Choose your power</h1><p>This choice defines which attribute increases your damage.</p><div class="power-cards"><button data-power="magic"><strong>✨ Magic</strong><small>Intelligence × 3 damage</small></button><button data-power="archer"><strong>🏹 Archer</strong><small>Agility × 3 damage</small></button><button data-power="healer"><strong>💚 Healer</strong><small>Intelligence × 3 damage</small></button></div><button class="back-title">Back</button></div></div>`;this.ui.querySelectorAll<HTMLElement>('[data-power]').forEach(button=>button.onclick=()=>this.launch(false,button.dataset.power as PowerType));this.ui.querySelector('.back-title')?.addEventListener('click',()=>this.showTitle());}
private launch(continuing:boolean,powerType?:PowerType){const data=continuing?this.save.load():null;this.ui.innerHTML='';let menu!:PauseMenu;const hud=new Hud(this.ui,()=>{menu.toggle();if(this.world)this.world.paused=menu.isOpen();});this.world=new WorldScene(this.engine,this.ui,hud,data,powerType,()=>this.showGameOver());menu=new PauseMenu(this.ui,this.world.player.state,()=>{menu.toggle(false);this.world!.paused=false;},()=>{this.save.save(this.world!.snapshot());hud.toast('Game saved');});new VirtualJoystick(this.ui,this.world.input);let last=performance.now();this.engine.runRenderLoop(()=>{const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;this.world!.update(dt);this.world!.scene.render();});}
private showGameOver(){this.save.clear();const overlay=document.createElement('div');overlay.className='overlay game-over';overlay.innerHTML=`<div class="panel"><h1>Game Over</h1><p class="empty">The base core was destroyed.</p><p>Your progress has been lost. Begin a new adventure.</p><button>Start New Game</button></div>`;this.ui.append(overlay);overlay.querySelector('button')?.addEventListener('click',()=>{this.engine.stopRenderLoop();this.world=undefined;this.showPowerSelection();});}}
