export type MonsterType = "crawler" | "wailer" | "ghost" | "bear" | "bat";
export const MONSTERS_CONFIG = {
  crawler: {
    level: 1,
    health: 16,
    damage: 22,
    experienceReward: 12,
    coinDrop: { chance: 0.35, amount: 2 },
    meatDrop: { chance: 0, amount: 0 },
    attackCooldownMs: 1200,
    movementSpeed: 2.4,
    detectionRadius: 8,
    leashRadius: 16,
    attackRadius: 1.25,
  },
  wailer: {
    level: 2,
    health: 32,
    damage: 28,
    experienceReward: 25,
    coinDrop: { chance: 0.5, amount: 4 },
    meatDrop: { chance: 0, amount: 0 },
    attackCooldownMs: 1800,
    movementSpeed: 1.15,
    detectionRadius: 12,
    leashRadius: 18,
    attackRadius: 5,
  },
  ghost: {
    level: 3,
    health: 60,
    damage: 60,
    experienceReward: 50,
    coinDrop: { chance: 0.4, amount: 20 },
    meatDrop: { chance: 0, amount: 0 },
    attackCooldownMs: 1500,
    movementSpeed: 2.5,
    detectionRadius: 18,
    leashRadius: 24,
    attackRadius: 1.5,
    invisibility: {
      visibleDurationMs: 3000,
      invisibleDurationMs: 2000,
      warningBlinks: 2,
      blinkIntervalMs: 150,
    },
  },
  bear: {
    category: "boss",
    level: 10,
    health: 400,
    damage: 500,
    experienceReward: 400,
    coinDrop: { chance: 1, amount: 8000 },
    meatDrop: { chance: 1, amount: 10 },
    attackCooldownMs: 2800,
    movementSpeed: 4.5,
    detectionRadius: 1000,
    leashRadius: 1000,
    attackRadius: 2.2,
  },
  bat: {
    level: 2,
    unlockPlayerLevel: 30,
    health: 70,
    damage: 30,
    experienceReward: 20,
    coinDrop: { chance: 0.25, amount: 3 },
    meatDrop: { chance: 0.3, amount: 1 },
    attackCooldownMs: 1100,
    movementSpeed: 4.2,
    darknessSpeedMultiplier: 2,
    detectionRadius: 16,
    leashRadius: 30,
    wanderRadius: 30,
    attackRadius: 1.1,
  },
} as const;
export const MONSTER_SPAWN_CONFIG = {
  enabled: true,
  maxMonsters: 30, //15
  initialPopulationPercent: 0.45,
  minDistanceFromPlayer: 18,
  maxSpawnAttempts: 30,
  obstacleClearance: 1.5,
  groupRadius: 3,
  retryDelayMs: 1000,
  respawn: { defaultDelayMs: 10000 }, //15000
  monsters: {
    crawler: {
      enabled: true,
      maxPlayerLevel: 29,
      maxAlive: 10,
      respawnDelayMs: 12000,
      spawnGroupSize: 2,
      spawnWeight: 70,
    },
    wailer: {
      enabled: true,
      maxAlive: 4,
      respawnDelayMs: 18000,
      spawnGroupSize: 1,
      spawnWeight: 30,
    },
    ghost: {
      enabled: true,
      maxAlive: 9,
      respawnDelayMs: 2000,
      spawnGroupSize: 2,
      spawnWeight: 20,
    },
    bear: {
      enabled: false,
      maxAlive: 1,
      respawnDelayMs: 60000,
      spawnGroupSize: 1,
      spawnWeight: 0,
    },
    bat: {
      enabled: true,
      maxAlive: 12,
      minimumAliveAfterUnlock: 6,
      respawnDelayMs: 15000,
      spawnGroupSize: 6,
      spawnWeight: 60,
      unlockPlayerLevel: 30,
    },
  },
  forcedSpawnRetryMs: 2000,
  debug: { showSpawnAreas: false },
} as const;
