export type MonsterType = "crawler" | "wailer" | "ghost";
export const MONSTERS_CONFIG = {
  crawler: {
    level: 1,
    health: 16,
    damage: 22,
    experienceReward: 12,
    coinDrop: { chance: 0.35, amount: 2 },
    attackCooldownMs: 1200,
    movementSpeed: 2.4,
    detectionRadius: 8,
    leashRadius: 16,
    attackRadius: 1.25,
  },
  wailer: {
    level: 2,
    health: 32,
    damage: 28,
    experienceReward: 25,
    coinDrop: { chance: 0.5, amount: 4 },
    attackCooldownMs: 1800,
    movementSpeed: 1.15,
    detectionRadius: 12,
    leashRadius: 18,
    attackRadius: 5,
  },
  ghost: {
    level: 3,
    health: 60,
    damage: 60,
    experienceReward: 50,
    coinDrop: { chance: 0.4, amount: 20 },
    attackCooldownMs: 1500,
    movementSpeed: 2,
    detectionRadius: 18,
    leashRadius: 24,
    attackRadius: 1.5,
    invisibility: {
      visibleDurationMs: 3000,
      invisibleDurationMs: 2000,
      warningBlinks: 2,
      blinkIntervalMs: 150,
    },
  },
} as const;
export const MONSTER_SPAWN_CONFIG = {
  enabled: true,
  maxMonsters: 14,
  initialPopulationPercent: 0.45,
  minDistanceFromPlayer: 18,
  maxSpawnAttempts: 30,
  obstacleClearance: 1.5,
  groupRadius: 3,
  retryDelayMs: 1000,
  respawn: { defaultDelayMs: 15000 },
  monsters: {
    crawler: {
      enabled: true,
      maxAlive: 10,
      respawnDelayMs: 12000,
      spawnGroupSize: 2,
      spawnWeight: 70,
    },
    wailer: {
      enabled: true,
      maxAlive: 4,
      respawnDelayMs: 18000,
      spawnGroupSize: 1,
      spawnWeight: 30,
    },
    ghost: {
      enabled: true,
      maxAlive: 5,
      respawnDelayMs: 2000,
      spawnGroupSize: 1,
      spawnWeight: 20,
    },
  },
  debug: { showSpawnAreas: false },
} as const;
