import type { BaseState,PlayerState } from '../core/types';import { maxHealth } from '../systems/StatsSystem';import { requiredXP } from '../systems/ExperienceSystem';
export class Hud{
  el:HTMLElement;
  constructor(root:HTMLElement,onMenu:()=>void,onShop:()=>void,onCharacter:()=>void,onAutoplay:(enabled:boolean)=>void,onBuild:()=>void){this.el=document.createElement('div');this.el.className='hud';this.el.innerHTML=`<div class="top-actions"><button class="menu-btn">☰ Menu</button><button class="character-btn" aria-label="Open character status" title="Character status">👤</button><button class="shop-btn" aria-label="Open shop" title="Shop">🛒</button><button class="build-btn" aria-label="Build defenses" title="Build defenses">🏰 BUILD</button><div class="coin-total" aria-label="Coins">● <span>0</span></div><label class="autoplay-switch"><input type="checkbox"><span></span><b>Autoplay</b></label></div><div class="meters"><b class="level"></b><label>HP <span class="hptext"></span><i class="bar hp"><i></i></i></label><label>XP <span class="xptext"></span><i class="bar xp"><i></i></i></label></div><div class="base-status"><b class="raid-label"></b><span class="base-health"></span><i class="base-bar"><i></i></i></div><div class="toast"></div>`;root.append(this.el);this.el.querySelector('.menu-btn')?.addEventListener('click',onMenu);this.el.querySelector('.shop-btn')?.addEventListener('click',onShop);this.el.querySelector('.character-btn')?.addEventListener('click',onCharacter);this.el.querySelector('.build-btn')?.addEventListener('click',onBuild);this.el.querySelector<HTMLInputElement>('.autoplay-switch input')?.addEventListener('change',event=>onAutoplay((event.currentTarget as HTMLInputElement).checked));}
  update(player:PlayerState){const maximum=maxHealth(player.stats.vitality,player.level),required=requiredXP(player.level);this.set('.level',`LV ${player.level}`);this.set('.hptext',`${Math.ceil(player.currentHealth)} / ${maximum}`);this.set('.xptext',`${player.xp} / ${required}`);this.set('.coin-total span',String(player.coins));this.width('.hp i',player.currentHealth/maximum*100);this.width('.xp i',player.xp/required*100);}
  updateBase(base:BaseState,maximumHealth:number){const seconds=Math.ceil(base.remainingTimeMs/1000);this.set('.raid-label',base.raidActive?`⚠ BASE UNDER ATTACK · ${seconds}s`:`Next raid · ${seconds}s`);this.set('.base-health',`Core ${base.currentHealth} / ${maximumHealth}`);this.width('.base-bar i',base.currentHealth/maximumHealth*100);}
  toast(value:string){const element=this.el.querySelector('.toast') as HTMLElement;element.textContent=value;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),1200);}
  private set(selector:string,value:string){const element=this.el.querySelector(selector);if(element)element.textContent=value;}private width(selector:string,value:number){(this.el.querySelector(selector) as HTMLElement).style.width=`${Math.max(0,value)}%`;}
}
