import type { ArcherWeaponConfig } from '../config/archerWeaponsConfig';import type { ArcherBootConfig } from '../config/archerBootsConfig';import type { PowerType } from '../core/types';
export type ShopView={powerType:PowerType;coins:number;baseHealth:number;baseMaxHealth:number;cost:number;healthRestore:number;currentWeapon?:ArcherWeaponConfig;nextWeapon?:ArcherWeaponConfig;currentDamage:number;nextDamage:number|null;currentBoots?:ArcherBootConfig;nextBoots?:ArcherBootConfig;currentSpeed:number;nextSpeed:number|null;currentSpeedBonusPercent:number;nextSpeedBonusPercent:number|null};
type EquipmentView={name:string;level:number;rarity:string;image?:string;color:string;bonusLabel:string};
const equipmentCard=(item:EquipmentView,label:string,icon:string)=>`<article class="weapon-card rarity-${item.rarity}"><span class="weapon-label">${label}</span><div class="weapon-picture" style="--weapon-color:${item.color}">${item.image?`<img src="${item.image}" alt="${item.name}" onerror="this.hidden=true">`:''}<span>${icon}</span></div><div><small>${item.rarity} · Level ${item.level}</small><h2>${item.name}</h2><b>${item.bonusLabel}</b></div></article>`;
export class ShopMenu{
  el:HTMLElement;private category:'weapons'|'boots'='weapons';
  constructor(root:HTMLElement,private view:()=>ShopView,private buyBase:()=>string,private upgradeWeapon:()=>string,private upgradeBoots:()=>string,private close:()=>void){this.el=document.createElement('div');this.el.className='overlay hidden';root.append(this.el);this.render();}
  toggle(open?:boolean){const shouldOpen=open??!this.isOpen();this.el.classList.toggle('hidden',!shouldOpen);this.render();}isOpen(){return!this.el.classList.contains('hidden');}
  private weaponSection(state:ShopView){if(state.powerType!=='archer'||!state.currentWeapon)return'<section class="weapon-shop unavailable"><h2>Equipment</h2><p>Equipment upgrades are exclusive to the Archer class.</p></section>';const current=state.currentWeapon,next=state.nextWeapon;return`<section class="weapon-shop"><div class="weapon-grid">${equipmentCard({name:current.name,level:current.level,rarity:current.rarity,image:current.image,color:current.placeholderColor,bonusLabel:`+${current.damageBonusPercent}% damage`},'Equipped','🏹')}${next?equipmentCard({name:next.name,level:next.level,rarity:next.rarity,image:next.image,color:next.placeholderColor,bonusLabel:`+${next.damageBonusPercent}% damage`},'Next upgrade','🏹'):'<article class="weapon-card max-weapon"><span>🏆</span><h2>MAX LEVEL</h2><p>Celestial Bow · +24%</p></article>'}</div>${next?`<div class="damage-preview"><span>Damage now <b>${state.currentDamage}</b></span><span>After upgrade <b>${state.nextDamage}</b></span></div><button data-upgrade-weapon ${state.coins<next.price?'disabled':''}>Buy ${next.name} · ● ${next.price} Coins</button>${state.coins<next.price?'<p class="not-enough">Not enough Coins</p>':''}`:'<button disabled>MAX LEVEL · +24% damage</button>'}</section>`;}
  private bootsSection(state:ShopView){if(state.powerType!=='archer')return'<section class="weapon-shop unavailable"><h2>Equipment</h2><p>Equipment upgrades are exclusive to the Archer class.</p></section>';const current=state.currentBoots,next=state.nextBoots,currentView:EquipmentView=current?{name:current.name,level:current.level,rarity:current.rarity,image:current.image,color:current.placeholderColor,bonusLabel:`+${current.movementSpeedBonusPercent}% movement speed`}:{name:'No Boots',level:0,rarity:'common',color:'#88745f',bonusLabel:'+0% movement speed'};return`<section class="weapon-shop"><div class="weapon-grid">${equipmentCard(currentView,'Equipped','🥾')}${next?equipmentCard({name:next.name,level:next.level,rarity:next.rarity,image:next.image,color:next.placeholderColor,bonusLabel:`+${next.movementSpeedBonusPercent}% movement speed`},'Next upgrade','🥾'):'<article class="weapon-card max-weapon"><span>🏆</span><h2>MAX LEVEL</h2><p>Celestial Striders · +24%</p></article>'}</div>${next?`<div class="damage-preview"><span>Speed <b>${state.currentSpeed.toFixed(2)} → ${state.nextSpeed?.toFixed(2)}</b></span><span>Total bonus <b>+${state.currentSpeedBonusPercent.toFixed(1)}% → +${state.nextSpeedBonusPercent?.toFixed(1)}%</b></span></div><button data-upgrade-boots ${state.coins<next.price?'disabled':''}>${current?'Upgrade':'Buy'} ${next.name} · ● ${next.price} Coins</button>${state.coins<next.price?'<p class="not-enough">Not enough Coins</p>':''}`:'<button disabled>MAX LEVEL · +24% movement speed</button>'}</section>`;}
  private render(message=''){const state=this.view(),full=state.baseHealth>=state.baseMaxHealth,repairDisabled=state.coins<state.cost||full,equipment=this.category==='weapons'?this.weaponSection(state):this.bootsSection(state);this.el.innerHTML=`<div class="panel shop-panel modal-panel"><button class="modal-close" data-close aria-label="Close shop" title="Close">×</button><h1>Equipment Shop</h1><div class="shop-balances"><span>● ${state.coins} Coins</span></div><div class="shop-tabs"><button data-category="weapons" class="${this.category==='weapons'?'active':''}">🏹 Weapons</button><button data-category="boots" class="${this.category==='boots'?'active':''}">🥾 Boots</button></div>${equipment}<section class="shop-item"><div class="shop-fire">🔥</div><div><h2>Repair the Core</h2><p>Restore up to ${state.healthRestore} base HP.</p><small>Core: ${state.baseHealth} / ${state.baseMaxHealth}</small></div><button data-buy-base ${repairDisabled?'disabled':''}>Buy · ● ${state.cost} Coins</button></section>${full?'<p class="hint">The core is already at full health.</p>':''}<p class="shop-message">${message}</p><button data-close>Return to Game</button></div>`;this.el.querySelectorAll<HTMLElement>('[data-category]').forEach(button=>button.onclick=()=>{this.category=button.dataset.category as 'weapons'|'boots';this.render();});this.el.querySelector('[data-buy-base]')?.addEventListener('click',()=>this.render(this.buyBase()));this.el.querySelector('[data-upgrade-weapon]')?.addEventListener('click',()=>this.render(this.upgradeWeapon()));this.el.querySelector('[data-upgrade-boots]')?.addEventListener('click',()=>this.render(this.upgradeBoots()));this.el.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',this.close));}
}
