import { beforeEach,describe,expect,it } from 'vitest';import { ARCHER_BOOTS,getArcherBoots,getNextArcherBoots } from '../config/archerBootsConfig';import { GAME_CONFIG } from '../config/gameConfig';import { createPlayerState } from '../core/GameState';import type { SaveData } from '../core/types';import { purchaseArcherBoots } from './ArcherBootsSystem';import { SaveSystem } from './SaveSystem';import { bootsSpeedBonusPercent,criticalChance,movementSpeed,powerDamage } from './StatsSystem';
describe('Archer Boots',()=>{
  it('has 12 configured levels',()=>expect(ARCHER_BOOTS).toHaveLength(12));
  it('level 0 has no speed bonus',()=>expect(bootsSpeedBonusPercent(0)).toBe(0));
  it('level 1 gives 2%',()=>expect(bootsSpeedBonusPercent(1)).toBe(2));
  it('level 12 gives 24%',()=>expect(bootsSpeedBonusPercent(12)).toBe(24));
  it('does not alter agility',()=>{const player=createPlayerState('archer'),agility=player.stats.agility;player.coins=75;purchaseArcherBoots(player);expect(player.stats.agility).toBe(agility);});
  it('does not alter Archer damage or critical chance',()=>{const player=createPlayerState('archer'),damage=powerDamage('archer',player.stats,player.archerWeaponLevel),critical=criticalChance(player.stats.agility);player.coins=75;purchaseArcherBoots(player);expect([powerDamage('archer',player.stats,player.archerWeaponLevel),criticalChance(player.stats.agility)]).toEqual([damage,critical]);});
  it('adds level, agility and boots bonuses without compounding',()=>expect(movementSpeed(60,10,5)).toBeCloseTo(GAME_CONFIG.player.movement.baseSpeed*1.45));
  it('purchase spends Coins, levels up and auto equips',()=>{const player=createPlayerState('archer');player.coins=75;expect(purchaseArcherBoots(player).success).toBe(true);expect([player.coins,player.bootsLevel,player.equipment.boots]).toEqual([0,1,'traveler-boots']);});
  it('uses the same levels and prices for Mage',()=>{const player=createPlayerState('magic'),boots=getArcherBoots(1)!;player.coins=boots.price;expect(purchaseArcherBoots(player).success).toBe(true);expect([player.coins,player.bootsLevel,player.equipment.boots]).toEqual([0,1,'traveler-boots']);});
  it('does not purchase without Coins or make balance negative',()=>{const player=createPlayerState('archer');player.coins=74;expect(purchaseArcherBoots(player).success).toBe(false);expect([player.coins,player.bootsLevel]).toEqual([74,0]);});
  it('does not skip levels',()=>{const player=createPlayerState('archer');player.coins=1000;expect(purchaseArcherBoots(player,2).success).toBe(false);expect(player.bootsLevel).toBe(0);});
  it('does not pass level 12 and has no next item at max',()=>{const player=createPlayerState('archer');player.bootsLevel=12;player.equipment.boots='celestial-striders';expect(purchaseArcherBoots(player).success).toBe(false);expect(getNextArcherBoots(12)).toBeUndefined();});
  it('uses config as source of truth',()=>expect(getArcherBoots(8)).toMatchObject({id:'stormstride-boots',movementSpeedBonusPercent:16,price:3800,rarity:'rare'}));
  it('shop preview can use the exact StatsSystem function',()=>{const player=createPlayerState('archer');expect([movementSpeed(player.level,player.stats.agility,0),movementSpeed(player.level,player.stats.agility,1)]).toEqual([movementSpeed(player.level,player.stats.agility,0),movementSpeed(player.level,player.stats.agility,1)]);});
});
describe('Boots save compatibility',()=>{
  const memory=new Map<string,string>();beforeEach(()=>{memory.clear();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)}});});
  it('preserves Coins and boots level and reconstructs equipment',()=>{const player=createPlayerState('archer');player.coins=321;player.bootsLevel=8;const data={version:1,player,world:{mapId:'green-fields',monsters:[],npcs:[],objects:[]}} satisfies SaveData;const saves=new SaveSystem();saves.save(data);const loaded=saves.load();expect([loaded?.player.coins,loaded?.player.bootsLevel,loaded?.player.equipment.boots]).toEqual([321,8,'stormstride-boots']);expect(movementSpeed(loaded!.player.level,loaded!.player.stats.agility,loaded!.player.bootsLevel)).toBe(movementSpeed(player.level,player.stats.agility,8));});
  it('reconstructs equipped boots for Mage',()=>{const player=createPlayerState('magic');player.bootsLevel=8;const data={version:1,player,world:{mapId:'green-fields',monsters:[],npcs:[],objects:[]}} satisfies SaveData;const saves=new SaveSystem();saves.save(data);expect(saves.load()?.player.equipment.boots).toBe('stormstride-boots');});
  it('migrates legacy Gold to Coins and removes Gold on next save',()=>{const player=createPlayerState('archer') as unknown as Record<string,unknown>;delete player.coins;delete player.bootsLevel;player.gold=777;memory.set(GAME_CONFIG.saveKey,JSON.stringify({version:1,player,world:{mapId:'green-fields',monsters:[],npcs:[],objects:[]}}));const saves=new SaveSystem(),loaded=saves.load()!;expect([loaded.player.coins,loaded.player.bootsLevel]).toEqual([777,0]);saves.save(loaded);expect(JSON.parse(memory.get(GAME_CONFIG.saveKey)!).player).not.toHaveProperty('gold');});
});
