import { describe,expect,it } from 'vitest';
import { createPlayerState } from '../core/GameState';
import type { AutoplayContext,AutoplayMonster } from './AutoplaySystem';
import { AutoplaySystem } from './AutoplaySystem';
import { maxHealth } from './StatsSystem';

const position={x:0,z:0},crawler:AutoplayMonster={id:'crawler-1',type:'crawler',alive:true,health:16,position:{x:6,z:0}},wailer:AutoplayMonster={id:'wailer-1',type:'wailer',alive:true,health:32,position:{x:6,z:0}};
const bear:AutoplayMonster={id:'bear-1',type:'bear',alive:true,health:3000,position:{x:10,z:0}};
const context=(values:Partial<AutoplayContext>={}):AutoplayContext=>({darknessActive:false,darknessRemainingMs:30000,raidActive:false,corePosition:{x:0,z:0},coreHealth:300,coreMaxHealth:300,...values});

describe('autoplay decisions',()=>{
  it('hunts a safe living monster',()=>{const player=createPlayerState('archer');expect(new AutoplaySystem().decide(player,position,[crawler],[])).toMatchObject({mode:'attack',monsterId:'crawler-1'});});
  it('walks toward a monster outside Mage attack range',()=>{const player=createPlayerState('magic'),far={...crawler,position:{x:20,z:0}};expect(new AutoplaySystem().decide(player,position,[far],[])).toMatchObject({mode:'hunt',monsterId:'crawler-1',destination:far.position});});
  it('collects Coins before hunting when the area is safe',()=>{const player=createPlayerState('magic'),coin={x:1,z:1};expect(new AutoplaySystem().decide(player,position,[{...crawler,position:{x:20,z:0}}],[coin])).toEqual({mode:'coins',destination:coin});});
  it('retreats from the nearest monster at critical health',()=>{const player=createPlayerState('magic');player.currentHealth=maxHealth(player.stats.vitality,player.level)*.3;const decision=new AutoplaySystem().decide(player,position,[crawler],[]);expect(decision.mode).toBe('retreat');expect(decision.destination!.x).toBeLessThan(0);});
  it('does not approach a distant monster whose expected damage is unsafe for the Mage',()=>{const player=createPlayerState('magic');player.currentHealth=60;expect(new AutoplaySystem().decide(player,position,[wailer],[]).mode).toBe('idle');});
  it('ignores dead monsters',()=>{const player=createPlayerState('magic');expect(new AutoplaySystem().decide(player,position,[{...crawler,alive:false}],[]).mode).toBe('idle');});
  it('uses a potion only when nearby danger could kill the player',()=>{const player=createPlayerState();player.healthPotions=1;player.currentHealth=20;const autoplay=new AutoplaySystem();expect(autoplay.decideActions(player,position,[{...crawler,position:{x:2,z:0}}],context())).toContain('use-potion');player.currentHealth=maxHealth(player.stats.vitality,player.level)*.9;expect(autoplay.decideActions(player,position,[crawler],context())).not.toContain('use-potion');});
  it('uses gas and turns on the lantern only during darkness',()=>{const player=createPlayerState();player.gasCanisters=1;const autoplay=new AutoplaySystem();expect(autoplay.decideActions(player,position,[],context({darknessActive:true,darknessRemainingMs:4000}))).toEqual(['refill-lantern','toggle-lantern']);player.lanternFuel=50;expect(autoplay.decideActions(player,position,[],context({darknessActive:true,darknessRemainingMs:4000}))).toEqual(['toggle-lantern']);});
  it('does not waste gas while the lantern still has useful fuel',()=>{const player=createPlayerState();player.gasCanisters=3;player.lanternFuel=50;player.lanternOn=true;expect(new AutoplaySystem().decideActions(player,position,[],context({darknessActive:true,darknessRemainingMs:4000}))).toEqual([]);});
  it('turns the lantern off outside darkness',()=>{const player=createPlayerState();player.lanternFuel=50;player.lanternOn=true;expect(new AutoplaySystem().decideActions(player,position,[],context())).toEqual(['toggle-lantern']);});
  it('prioritizes the monster closest to the Core during a raid',()=>{const player=createPlayerState('archer'),nearCore={...crawler,id:'core-threat',position:{x:1,z:0}},nearPlayer={...crawler,id:'player-threat',position:{x:8,z:0}};expect(new AutoplaySystem().decide(player,{x:8,z:0},[nearPlayer,nearCore],[],context({raidActive:true})).monsterId).toBe('core-threat');});
  it('returns to defend the Core when a raid target is not visible',()=>{const player=createPlayerState();expect(new AutoplaySystem().decide(player,{x:8,z:8},[],[],context({raidActive:true}))).toEqual({mode:'defend',destination:{x:0,z:0}});});
  it('prioritizes a distant boss over Coins and an active raid',()=>{const player=createPlayerState('archer');expect(new AutoplaySystem().decide(player,position,[crawler,bear],[{x:1,z:0}],context({raidActive:true}))).toMatchObject({mode:'attack',monsterId:'bear-1'});});
  it('attacks while retreating when the boss gets dangerously close',()=>{const player=createPlayerState('archer'),closeBoss={...bear,position:{x:2,z:0}};const decision=new AutoplaySystem().decide(player,position,[closeBoss],[]);expect(decision).toMatchObject({mode:'kite',monsterId:'bear-1'});expect(decision.destination!.x).toBeLessThan(0);});
  it('buys potions and keeps a larger reserve while a boss is alive',()=>{const player=createPlayerState();player.healthPotions=0;expect(new AutoplaySystem().decidePurchase(player,[bear],context())).toBe('buy-potion');player.healthPotions=6;player.gasCanisters=2;expect(new AutoplaySystem().decidePurchase(player,[bear],context())).toBeNull();});
  it('repairs a damaged Core before building normal consumable reserves',()=>{const player=createPlayerState();expect(new AutoplaySystem().decidePurchase(player,[],context({coreHealth:100}))).toBe('repair-core');});
  it('buys lantern gas when fuel and reserve are low',()=>{const player=createPlayerState();player.healthPotions=3;player.gasCanisters=0;player.lanternFuel=0;expect(new AutoplaySystem().decidePurchase(player,[],context())).toBe('buy-gas');});
  it('explores instead of standing still when nothing is visible in darkness',()=>{const player=createPlayerState();const decision=new AutoplaySystem().decide(player,position,[],[],context({darknessActive:true}));expect(decision.mode).toBe('explore');expect(decision.destination).toBeDefined();expect(Math.hypot(decision.destination!.x,decision.destination!.z)).toBeGreaterThan(1);});
  it('abandons dark exploration as soon as an opponent becomes visible',()=>{const player=createPlayerState('archer'),autoplay=new AutoplaySystem();autoplay.decide(player,position,[],[],context({darknessActive:true}));expect(autoplay.decide(player,position,[crawler],[],context({darknessActive:true}))).toMatchObject({mode:'attack',monsterId:'crawler-1'});});
  it('makes the Mage cast while retreating from a nearby enemy',()=>{const player=createPlayerState('magic'),near={...crawler,position:{x:2,z:0}},decision=new AutoplaySystem().decide(player,position,[near],[],context());expect(decision).toMatchObject({mode:'kite',monsterId:'crawler-1'});expect(decision.destination!.x).toBeLessThan(0);});
});
