import { Color3,MeshBuilder,StandardMaterial,TransformNode,type Scene } from '@babylonjs/core';import { GAME_CONFIG } from '../config/gameConfig';import { MONSTERS_CONFIG,type MonsterType } from '../config/monstersConfig';import type { PlayerState,Vec2 } from '../core/types';
export const shouldDropCoins=(randomValue:number,chance:number)=>randomValue<chance;export const addCoins=(current:number,amount:number)=>current+amount;
type CoinPickup={root:TransformNode;amount:number;phase:number};
export class CoinPickupSystem {
  private pickups:CoinPickup[]=[];
  constructor(private scene:Scene,private player:PlayerState,private playerPosition:()=>Vec2,private onCollected:(amount:number)=>void,private random:()=>number=Math.random){}
  tryDrop(type:MonsterType,position:Vec2){const drop=MONSTERS_CONFIG[type].coinDrop;if(!shouldDropCoins(this.random(),drop.chance))return false;this.pickups.push({root:this.createCoin(position),amount:drop.amount,phase:this.random()*Math.PI*2});return true;}
  positions():Vec2[]{return this.pickups.map(pickup=>({x:pickup.root.position.x,z:pickup.root.position.z}));}
  update(dt:number){const config=GAME_CONFIG.pickups.coin,playerPosition=this.playerPosition();for(let index=this.pickups.length-1;index>=0;index--){const pickup=this.pickups[index];if(!pickup)continue;pickup.phase+=dt*3;pickup.root.rotation.y+=dt*config.rotationSpeed;pickup.root.position.y=config.hoverHeight+Math.sin(pickup.phase)*.08;if(Math.hypot(playerPosition.x-pickup.root.position.x,playerPosition.z-pickup.root.position.z)<=config.pickupRadius){this.player.coins=addCoins(this.player.coins,pickup.amount);pickup.root.dispose(false,true);this.pickups.splice(index,1);this.onCollected(pickup.amount);}}}
  private createCoin(position:Vec2){const root=new TransformNode(`coin-${Date.now()}`,this.scene);root.position.set(position.x,GAME_CONFIG.pickups.coin.hoverHeight,position.z);const material=new StandardMaterial('coin-material',this.scene);material.diffuseColor=Color3.FromHexString('#F5B82E');material.emissiveColor=Color3.FromHexString('#7A4B08');const coin=MeshBuilder.CreateCylinder('coin',{height:.12,diameter:.48,tessellation:20},this.scene);coin.parent=root;coin.rotation.z=Math.PI/2;coin.material=material;return root;}
}
