import {Color3,MeshBuilder,StandardMaterial,TransformNode,Vector3,type Scene} from "@babylonjs/core";
import {getStaff,MAGE_CONFIG,type MageSpellType} from "../config/mageConfig";
import {MONSTERS_CONFIG} from "../config/monstersConfig";
import type {Monster} from "../entities/Monster";
import type {Player} from "../entities/Player";
import {addExperience} from "./ExperienceSystem";
import {consumeAttackHunger} from "./HungerSystem";
import {attackRange,criticalChance,powerDamage} from "./StatsSystem";
import {GAME_CONFIG} from "../config/gameConfig";

type Projectile={root:TransformNode;target:Monster;lastTarget:Vector3;spell:MageSpellType};
export const targetsInsideRadius=<T extends {position:{x:number;z:number}}>(center:{x:number;z:number},targets:T[],radius:number)=>targets.filter(target=>Math.hypot(target.position.x-center.x,target.position.z-center.z)<=radius);
export const rollMageDamage=(baseDamage:number,agility:number,random:()=>number=Math.random)=>{const critical=random()*100<criticalChance(agility);return{critical,damage:Math.round(baseDamage*(critical?GAME_CONFIG.player.critical.damageMultiplier:1)*MAGE_CONFIG.combat.aoeDamageMultiplier)};};

export class MageCombatSystem{
  private cooldownMs=0;private projectiles:Projectile[]=[];
  constructor(private scene:Scene,private player:Player,private monsters:()=>Monster[],private feedback:(text:string,x:number,z:number,critical:boolean)=>void,private onMonsterKilled:(monster:Monster)=>void=()=>{},private onLevelUp:()=>void=()=>{}){}
  cast(target:Monster){if(this.player.state.powerType!=="magic"||this.cooldownMs>0||!target.isTargetable)return false;const dx=target.root.position.x-this.player.root.position.x,dz=target.root.position.z-this.player.root.position.z;if(Math.hypot(dx,dz)>attackRange("magic"))return false;this.cooldownMs=MAGE_CONFIG.combat.cooldownMs;consumeAttackHunger(this.player.state);this.player.root.rotation.y=Math.atan2(dx,dz);const spell=this.player.state.selectedSpell,start=new Vector3(this.player.root.position.x,1.65,this.player.root.position.z),root=this.createProjectile(spell);root.position.copyFrom(start);this.projectiles.push({root,target,lastTarget:new Vector3(target.root.position.x,1,target.root.position.z),spell});return true;}
  update(dt:number){this.cooldownMs=Math.max(0,this.cooldownMs-dt*1000);for(let index=this.projectiles.length-1;index>=0;index--){const projectile=this.projectiles[index];if(!projectile)continue;if(projectile.target.state.alive)projectile.lastTarget.set(projectile.target.root.position.x,1,projectile.target.root.position.z);const delta=projectile.lastTarget.subtract(projectile.root.position),distance=delta.length(),step=MAGE_CONFIG.combat.projectileSpeed*dt;if(distance<=step){this.impact(projectile);projectile.root.dispose(false,true);this.projectiles.splice(index,1);continue;}projectile.root.position.addInPlace(delta.scale(step/(distance||1)));projectile.root.rotation.y=Math.atan2(delta.x,delta.z);}}
  private impact(projectile:Projectile){const staff=getStaff(this.player.state.staffLevel),center={x:projectile.lastTarget.x,z:projectile.lastTarget.z},candidates=staff.aoeRadius>0?targetsInsideRadius(center,this.monsters().filter(monster=>monster.isTargetable).map(monster=>({monster,position:{x:monster.root.position.x,z:monster.root.position.z}})),staff.aoeRadius).map(value=>value.monster):projectile.target.isTargetable?[projectile.target]:[];for(const monster of new Set(candidates)){const {critical,damage}=rollMageDamage(powerDamage("magic",this.player.state.stats),this.player.state.stats.agility);this.feedback(String(damage),monster.root.position.x,monster.root.position.z,critical);if(monster.damage(damage)){const levels=addExperience(this.player.state,MONSTERS_CONFIG[monster.state.type].experienceReward);if(levels>0)this.onLevelUp();this.onMonsterKilled(monster);}}this.createImpact(projectile.spell,projectile.lastTarget,staff.aoeRadius);}
  private createProjectile(spell:MageSpellType){const root=new TransformNode(`mage-${spell}`,this.scene),color=spell==="ice-lance"?"#8eefff":"#fff36a",mat=new StandardMaterial(`${spell}-material`,this.scene);mat.diffuseColor=Color3.FromHexString(color);mat.emissiveColor=Color3.FromHexString(color);const shaft=MeshBuilder.CreateCylinder(`${spell}-shaft`,{height:1.05,diameter:.1,tessellation:spell==="ice-lance"?6:4},this.scene);shaft.parent=root;shaft.rotation.x=Math.PI/2;shaft.material=mat;const tip=MeshBuilder.CreateCylinder(`${spell}-tip`,{height:.35,diameterTop:0,diameterBottom:.22,tessellation:6},this.scene);tip.parent=root;tip.position.z=.68;tip.rotation.x=Math.PI/2;tip.material=mat;return root;}
  private createImpact(spell:MageSpellType,position:Vector3,radius:number){const color=spell==="ice-lance"?"#70e8ff":"#ffe85c",mat=new StandardMaterial(`${spell}-impact-material`,this.scene);mat.diffuseColor=Color3.FromHexString(color);mat.emissiveColor=Color3.FromHexString(color);const count=radius>0?8:4;for(let index=0;index<count;index++){const fragment=MeshBuilder.CreatePolyhedron(`${spell}-impact`,{type:1,size:.08},this.scene);fragment.position.set(position.x+Math.cos(index/count*Math.PI*2)*Math.max(.25,radius*.55),.35+index%3*.12,position.z+Math.sin(index/count*Math.PI*2)*Math.max(.25,radius*.55));fragment.material=mat;setTimeout(()=>fragment.dispose(false,true),280);}if(import.meta.env.DEV&&MAGE_CONFIG.debug.showMageAoERadius&&radius>0){const points=Array.from({length:33},(_,index)=>{const angle=index/32*Math.PI*2;return new Vector3(position.x+Math.cos(angle)*radius,.06,position.z+Math.sin(angle)*radius);}),ring=MeshBuilder.CreateLines("mage-aoe-debug",{points},this.scene);ring.color=Color3.FromHexString(color);setTimeout(()=>ring.dispose(false,true),500);}}
}
