import { GAME_CONFIG } from '../config/gameConfig'; import { getArcherWeapon } from '../config/archerWeaponsConfig'; import type { PlayerState, PowerType, Stats } from '../core/types';
export const maxHealth = (vitality: number, level = 1) => GAME_CONFIG.player.baseHealth + (vitality - 1) * GAME_CONFIG.player.healthPerVitality + (level - 1) * GAME_CONFIG.player.healthPerLevel;
export const criticalChance = (a: number) => a * GAME_CONFIG.player.critical.agilityMultiplier;
export const movementSpeed = (level: number, agility: number) => GAME_CONFIG.player.movement.baseSpeed * (1 + (level * GAME_CONFIG.player.movement.levelBonusPercent + agility * GAME_CONFIG.player.movement.agilityBonusPercent) / 100);
export const initialStatPoints = (level: number) => (level - 1) * GAME_CONFIG.player.statPointsPerLevel;
export const basePowerDamage = (powerType:PowerType,stats:Stats) => (powerType==='archer'?stats.agility:stats.intelligence)*GAME_CONFIG.player.attack.powerStatMultiplier;
export const weaponDamageBonusPercent = (weaponLevel:number) => getArcherWeapon(weaponLevel)?.damageBonusPercent??0;
export const powerDamage = (powerType:PowerType,stats:Stats,archerWeaponLevel=1) => Math.round(basePowerDamage(powerType,stats)*(powerType==='archer'?1+weaponDamageBonusPercent(archerWeaponLevel)/100:1));
export const attackRange = (powerType:PowerType) => GAME_CONFIG.player.attack.rangeByPower[powerType];
export const spendStat = (player: PlayerState, stat: keyof Stats) => { if (player.availableStatPoints < 1) return false; player.stats[stat]++; player.availableStatPoints--; if (stat === 'vitality') player.currentHealth += GAME_CONFIG.player.healthPerVitality; return true; };
export const resetStats = (player: PlayerState) => { player.stats={...GAME_CONFIG.player.initialStats};player.availableStatPoints=initialStatPoints(player.level);player.currentHealth=Math.min(player.currentHealth,maxHealth(player.stats.vitality,player.level)); };
