import { Color3,MeshBuilder,StandardMaterial,type AbstractMesh,type Scene } from '@babylonjs/core';import { HORROR_THEME_CONFIG } from '../config/horrorThemeConfig';import type { WorldObject } from '../world/worldData';
export const createWorldObject=(scene:Scene,o:WorldObject):AbstractMesh[]=>{const colors=HORROR_THEME_CONFIG.environment,material=(name:string,color:string)=>{const value=new StandardMaterial(name,scene);value.diffuseColor=Color3.FromHexString(color);value.specularColor=Color3.Black();return value;},meshes:AbstractMesh[]=[],add=(mesh:AbstractMesh,y:number,value:StandardMaterial)=>{mesh.position.set(o.position.x,y,o.position.z);mesh.rotation.y=o.rotation??0;mesh.material=value;mesh.receiveShadows=true;meshes.push(mesh);};
  if(o.type==='tree'){const wood=material('dead-wood',colors.deadWood),trunk=MeshBuilder.CreateCylinder(`${o.id}-trunk`,{height:4.2,diameterTop:.3,diameterBottom:.85,tessellation:7},scene);add(trunk,2.1,wood);trunk.rotation.z=.12;for(const [height,side] of [[2.6,-1],[3.25,1],[3.7,-1]] as const){const branch=MeshBuilder.CreateCylinder(`${o.id}-branch`,{height:1.7,diameterTop:.08,diameterBottom:.24,tessellation:6},scene);add(branch,height,wood);branch.rotation.z=side*.9;branch.rotation.y=(o.rotation??0)+height;}}
  if(o.type==='rock')add(MeshBuilder.CreatePolyhedron(o.id,{type:1,size:1},scene),.55,material('wet-rock',colors.wetRock));
  if(o.type==='campfire'){for(let index=0;index<5;index++){const log=MeshBuilder.CreateCylinder(`${o.id}-${index}`,{height:.65,diameter:.18},scene);log.rotation.z=Math.PI/2;log.rotation.y=index*Math.PI/5;add(log,.2,material('charred-log','#241B18'));}const flame=MeshBuilder.CreateSphere('beacon-flame',{diameter:.65,segments:8},scene);flame.scaling.y=1.5;const fire=material('warm-fire',colors.warmFire);fire.emissiveColor=Color3.FromHexString(colors.warmFire);add(flame,.65,fire);}
  if(o.type==='branch'){const branch=MeshBuilder.CreateCylinder(o.id,{height:2.2,diameterTop:.08,diameterBottom:.2,tessellation:6},scene);add(branch,.12,material('dead-branch',colors.deadBranches));branch.rotation.z=Math.PI/2;}
  if(o.type==='fence'){const wood=material('broken-fence',colors.deadWood);for(const offset of [-1,0,1]){const post=MeshBuilder.CreateBox(`${o.id}-post`,{width:.18,height:1.3,depth:.18},scene);post.position.x+=offset;add(post,.65,wood);}const rail=MeshBuilder.CreateBox(`${o.id}-rail`,{width:2.5,height:.16,depth:.14},scene);add(rail,.75,wood);rail.rotation.z=.12;}
  if(o.type==='crate')add(MeshBuilder.CreateBox(o.id,{size:1.1},scene),.55,material('old-crate',colors.mud));
  if(o.type==='ruin'){const stone=material('ruin-stone',colors.ruin);const wall=MeshBuilder.CreateBox(o.id,{width:3.2,height:2.2,depth:.35},scene);add(wall,1.1,stone);wall.rotation.z=.05;}
  if(o.type==='bones'){const bone=material('old-bones',colors.bone);for(let index=0;index<4;index++){const piece=MeshBuilder.CreateCylinder(`${o.id}-${index}`,{height:.8,diameter:.09,tessellation:6},scene);add(piece,.08,bone);piece.rotation.z=Math.PI/2;piece.rotation.y=index*.8;}}
  meshes.forEach(mesh=>mesh.scaling.scaleInPlace(o.scale??1));return meshes;};
