import type { MonsterType } from '../config/monstersConfig';
export type Vec2 = { x: number; z: number };
export type Stats = { strength: number; agility: number; intelligence: number; vitality: number };
export type PowerType = 'magic' | 'archer' | 'healer';
export type Equipment = { weapon: string|null; helmet: string|null; chest: string|null; boots: string|null };
export type PlayerState = { position: Vec2; mapId: string; powerType: PowerType; level: number; xp: number; coins: number; archerWeaponLevel: number; currentHealth: number; stats: Stats; availableStatPoints: number; inventory: string[]; equipment: Equipment };
export type MonsterState = { id: string; type: MonsterType; alive: boolean; health: number; position: Vec2; spawnPosition: Vec2 };
export type PendingRespawn = { type: MonsterType; remainingTimeMs: number };
export type BaseState = { currentHealth: number; raidActive: boolean; remainingTimeMs: number };
export type SaveData = { version: 1; player: PlayerState; world: { mapId: string; monsters: MonsterState[]; pendingRespawns?: PendingRespawn[]; base?: BaseState; npcs: never[]; objects: string[] } };
