import { Color3, Mesh, MeshBuilder, StandardMaterial, TransformNode, Vector3, type Scene } from '@babylonjs/core'; import type { MonsterState, Vec2 } from '../core/types'; import { MONSTERS_CONFIG } from '../config/monstersConfig'; import type { MonsterNavigationSystem } from '../systems/MonsterNavigationSystem'; import type { Player } from './Player';
export type MonsterAIState='IDLE'|'CHASING'|'ATTACKING'|'RETURNING'|'DEAD';
export class Monster {root:TransformNode; meshes:Mesh[]=[]; aiState:MonsterAIState; readyForRemoval=false; private cooldown=0; private deathTime=0;private navigation?:MonsterNavigationSystem;
 constructor(private scene:Scene,public state:MonsterState){this.root=new TransformNode(state.id,scene);this.root.position.set(state.position.x,0,state.position.z);this.aiState=state.alive?'IDLE':'DEAD';this.build();if(!state.alive)this.root.setEnabled(false);}
 private material(name:string,c:string){const m=new StandardMaterial(name,this.scene);m.diffuseColor=Color3.FromHexString(c);return m;}
 private add(mesh:Mesh,y:number,material:StandardMaterial){mesh.parent=this.root;mesh.position.y=y;mesh.material=material;this.meshes.push(mesh);}
 private build(){if(this.state.type==='slime'){this.add(MeshBuilder.CreateSphere('slime',{diameter:1.3,segments:16},this.scene),.55,this.material('slime-green','#65D66E'));this.root.scaling.y=.72;const eye=this.material('eye','#17202A');for(const x of [-.22,.22]){const e=MeshBuilder.CreateSphere('eye',{diameter:.16},this.scene);e.parent=this.root;e.position.set(x,.7,.48);e.material=eye;this.meshes.push(e);}}else{const green=this.material('stem','#398A45'),yellow=this.material('petals','#F8C43A'),brown=this.material('face','#6F3C24');this.add(MeshBuilder.CreateCylinder('stem',{height:1.4,diameter:.22},this.scene),.7,green);this.add(MeshBuilder.CreateCylinder('face',{height:.28,diameter:1.15,tessellation:16},this.scene),1.55,brown);this.meshes[1].rotation.x=Math.PI/2;for(let i=0;i<10;i++){const p=MeshBuilder.CreateSphere('petal',{diameter:.45},this.scene);p.parent=this.root;p.material=yellow;p.position.set(Math.sin(i*.628)*.66,1.55,Math.cos(i*.628)*.66);p.scaling.y=1.5;this.meshes.push(p);}}}
 update(player:Player,dt:number,damagePlayer:(n:number)=>void,paused:boolean,raid?:{active:boolean;position:Vec2;damageBase:(n:number)=>void}){if(paused||this.aiState==='DEAD')return;this.cooldown=Math.max(0,this.cooldown-dt*1000);const c=MONSTERS_CONFIG[this.state.type];if(raid?.active){const distance=Math.hypot(this.root.position.x-raid.position.x,this.root.position.z-raid.position.z);this.aiState=distance<=c.attackRadius?'ATTACKING':'CHASING';if(this.aiState==='CHASING')this.moveToward(raid.position.x,raid.position.z,c.movementSpeed,dt);if(this.aiState==='ATTACKING'&&this.cooldown===0){raid.damageBase(c.damage);this.cooldown=c.attackCooldownMs;}this.state.position={x:this.root.position.x,z:this.root.position.z};return;}const p=player.root.position,s=this.state.spawnPosition;const pd=Vector3.Distance(this.root.position,p),sd=Math.hypot(this.root.position.x-s.x,this.root.position.z-s.z);
 if(sd>c.leashRadius)this.aiState='RETURNING';else if(this.aiState==='IDLE'&&pd<c.detectionRadius)this.aiState='CHASING';else if(this.aiState==='CHASING'&&pd<=c.attackRadius)this.aiState='ATTACKING';else if(this.aiState==='ATTACKING'&&pd>c.attackRadius)this.aiState='CHASING';else if((this.aiState==='CHASING'||this.aiState==='ATTACKING')&&pd>c.detectionRadius*1.45)this.aiState='RETURNING';
 if(this.aiState==='CHASING')this.moveToward(p.x,p.z,c.movementSpeed,dt);if(this.aiState==='RETURNING'){this.moveToward(s.x,s.z,c.movementSpeed,dt);if(sd<.15)this.aiState='IDLE';}if(this.aiState==='ATTACKING'&&this.cooldown===0){damagePlayer(c.damage);this.cooldown=c.attackCooldownMs;}this.state.position={x:this.root.position.x,z:this.root.position.z};}
 setNavigation(navigation:MonsterNavigationSystem){this.navigation=navigation;}
 private moveToward(x:number,z:number,speed:number,dt:number){const waypoint=this.navigation?.getNextWaypoint(this.state.id,{x:this.root.position.x,z:this.root.position.z},{x,z})??{x,z},dx=waypoint.x-this.root.position.x,dz=waypoint.z-this.root.position.z,l=Math.hypot(dx,dz)||1;this.root.position.x+=dx/l*speed*dt;this.root.position.z+=dz/l*speed*dt;this.root.rotation.y=Math.atan2(dx,dz);}
 returnHome(){if(this.state.alive)this.aiState='RETURNING';}
 damage(n:number){if(!this.state.alive)return false;this.state.health=Math.max(0,this.state.health-n);this.meshes.forEach(m=>{const old=m.scaling.clone();m.scaling=old.scale(.85);setTimeout(()=>m.scaling=old,100)});if(this.state.health===0){this.state.alive=false;this.aiState='DEAD';this.deathTime=.45;return true;}return false;}
 animateDeath(dt:number){if(this.deathTime<=0)return;this.deathTime-=dt;this.root.scaling.scaleInPlace(Math.max(0,1-dt*3));this.root.rotation.y+=dt*8;if(this.deathTime<=0){this.root.setEnabled(false);this.readyForRemoval=true;}}
 dispose(){this.navigation?.clear(this.state.id);this.root.dispose(false,true);}
}
