import { Mesh,MeshBuilder,StandardMaterial,TransformNode,Color3,Vector3,type Scene } from '@babylonjs/core';import { GAME_CONFIG } from '../config/gameConfig';import type { PlayerState } from '../core/types';import { movementSpeed } from '../systems/StatsSystem';
const material=(scene:Scene,name:string,color:Color3)=>{const result=new StandardMaterial(name,scene);result.diffuseColor=color;return result;};
export class Player {root:TransformNode;body:Mesh;head:Mesh;leftArm:Mesh;rightArm:Mesh;leftLeg:Mesh;rightLeg:Mesh;private walk=0;private glowRemaining=0;private attackRemaining=0;private bowString?:Mesh;private heldArrow?:Mesh;private materials:StandardMaterial[];
constructor(scene:Scene,public state:PlayerState){this.root=new TransformNode('player',scene);this.root.position.set(state.position.x,0,state.position.z);const skin=material(scene,'skin',Color3.FromHexString('#F6B88B')),tunic=material(scene,'tunic',Color3.FromHexString('#4169E1')),dark=material(scene,'boots',Color3.FromHexString('#25304A'));this.materials=[skin,tunic,dark];this.body=MeshBuilder.CreateCapsule('body',{height:1.35,radius:.42},scene);this.body.material=tunic;this.body.parent=this.root;this.body.position.y=1.25;this.head=MeshBuilder.CreateSphere('head',{diameter:1.05,segments:16},scene);this.head.material=skin;this.head.parent=this.root;this.head.position.y=2.25;this.leftArm=this.limb(scene,'leftArm',-.56,1.35,skin);this.rightArm=this.limb(scene,'rightArm',.56,1.35,skin);this.leftLeg=this.limb(scene,'leftLeg',-.22,.48,dark);this.rightLeg=this.limb(scene,'rightLeg',.22,.48,dark);if(state.powerType==='archer')this.buildBow(scene);}
private limb(scene:Scene,name:string,x:number,y:number,value:StandardMaterial){const limb=MeshBuilder.CreateCapsule(name,{height:.9,radius:.16},scene);limb.material=value;limb.parent=this.root;limb.position.set(x,y,0);return limb;}
private buildBow(scene:Scene){const wood=material(scene,'bow-wood',Color3.FromHexString('#8B542F')),string=material(scene,'bow-string',Color3.FromHexString('#F4E7CA')),metal=material(scene,'arrow-head',Color3.FromHexString('#C9D2D6'));this.materials.push(wood,string,metal);const path=Array.from({length:9},(_,index)=>{const angle=-Math.PI/2+index*Math.PI/8;return new Vector3(Math.cos(angle)*.48,Math.sin(angle)*.78,0);});const bow=MeshBuilder.CreateTube('training-bow',{path,radius:.045,tessellation:8},scene);bow.parent=this.root;bow.position.set(.72,1.38,.08);bow.rotation.y=Math.PI/2;bow.material=wood;this.bowString=MeshBuilder.CreateTube('bow-string',{path:[new Vector3(0,-.78,0),new Vector3(-.12,0,0),new Vector3(0,.78,0)],radius:.012,tessellation:4},scene);this.bowString.parent=bow;this.bowString.material=string;this.heldArrow=MeshBuilder.CreateCylinder('held-arrow',{height:1.25,diameter:.045},scene);this.heldArrow.parent=this.root;this.heldArrow.position.set(.58,1.38,.12);this.heldArrow.rotation.x=Math.PI/2;this.heldArrow.material=metal;}
update(direction:{x:number;z:number},dt:number,blocked:(x:number,z:number)=>boolean){this.updateGlow(dt);const moving=Math.hypot(direction.x,direction.z)>.05;if(moving){const speed=movementSpeed(this.state.level,this.state.stats.agility),nextX=this.root.position.x+direction.x*speed*dt,nextZ=this.root.position.z+direction.z*speed*dt;if(!blocked(nextX,nextZ)){this.root.position.x=nextX;this.root.position.z=nextZ;}this.root.rotation.y=Math.atan2(direction.x,direction.z);this.walk+=dt*10;const swing=Math.sin(this.walk)*.55;this.leftArm.rotation.x=swing;this.rightArm.rotation.x=-swing;this.leftLeg.rotation.x=-swing;this.rightLeg.rotation.x=swing;this.body.position.y=1.25+Math.abs(Math.sin(this.walk))*.05;}else{this.leftArm.rotation.x=this.rightArm.rotation.x=this.leftLeg.rotation.x=this.rightLeg.rotation.x=0;this.body.position.y=1.25;}this.updateAttack(dt);this.state.position={x:this.root.position.x,z:this.root.position.z};}
playArcherAttack(){if(this.state.powerType==='archer')this.attackRemaining=GAME_CONFIG.player.attack.archerAnimationDurationSeconds;}
private updateAttack(dt:number){if(this.attackRemaining<=0){if(this.heldArrow)this.heldArrow.setEnabled(true);if(this.bowString)this.bowString.scaling.z=1;return;}this.attackRemaining=Math.max(0,this.attackRemaining-dt);const duration=GAME_CONFIG.player.attack.archerAnimationDurationSeconds,progress=1-this.attackRemaining/duration,draw=Math.sin(Math.min(1,progress*1.8)*Math.PI/2);this.leftArm.rotation.x=-1.15;this.leftArm.rotation.z=-.25;this.rightArm.rotation.x=-1.2;this.rightArm.rotation.z=.65*draw;if(this.bowString)this.bowString.scaling.z=1+draw*2.2;if(this.heldArrow)this.heldArrow.setEnabled(progress<.48);}
playLevelUpEffect(){this.glowRemaining=GAME_CONFIG.player.levelUpGlowDurationSeconds;}
private updateGlow(dt:number){this.glowRemaining=Math.max(0,this.glowRemaining-dt);const intensity=this.glowRemaining>0?.65+Math.sin(this.glowRemaining*25)*.25:0;this.materials.forEach(value=>value.emissiveColor=new Color3(intensity,intensity*.75,0));}
flashDamage(){this.root.scaling.y=.9;setTimeout(()=>this.root.scaling.y=1,100);}}
